### ISSUE TITLE
ArrayIndexOutOfBoundsException when using UtilizationModelPlanetLab

### ISSUE THREAD

**Issue by alexandredias3d** [manoelcampos/cloudsim-plus#152] opened 2018-08-17 15:47 UTC
The following exception was raised when trying to use the UtilizationModelPlanetLab:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 289
	at org.cloudbus.cloudsim.utilizationmodels.UtilizationModelPlanetLab.getUtilizationPerSec(UtilizationModelPlanetLab.java:160)
	at org.cloudbus.cloudsim.utilizationmodels.UtilizationModelPlanetLab.getUtilization(UtilizationModelPlanetLab.java:153)
	at org.cloudbus.cloudsim.utilizationmodels.UtilizationModelAbstract.getUtilization(UtilizationModelAbstract.java:69)
	at org.cloudbus.cloudsim.schedulers.cloudlet.CloudletSchedulerAbstract.getAbsoluteCloudletResourceUtilization(CloudletSchedulerAbstract.java:965)
	at org.cloudbus.cloudsim.schedulers.cloudlet.CloudletSchedulerAbstract.getAbsoluteCloudletCpuUtilizationForAllPes(CloudletSchedulerAbstract.java:901)
	at org.cloudbus.cloudsim.schedulers.cloudlet.CloudletSchedulerAbstract.lambda$getRequestedCpuPercentUtilization$11(CloudletSchedulerAbstract.java:887)
	at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:246)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:514)
	at java.base/java.util.stream.DoublePipeline.sum(DoublePipeline.java:425)
	at org.cloudbus.cloudsim.schedulers.cloudlet.CloudletSchedulerAbstract.getRequestedCpuPercentUtilization(CloudletSchedulerAbstract.java:888)
	at org.cloudbus.cloudsim.vms.VmSimple.getCpuPercentUsage(VmSimple.java:234)
	at org.cloudbus.cloudsim.vms.VmSimple.getTotalCpuMipsUsage(VmSimple.java:244)
	at org.cloudbus.cloudsim.vms.VmSimple.getTotalCpuMipsUsage(VmSimple.java:239)
	at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:246)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:514)
	at java.base/java.util.stream.DoublePipeline.sum(DoublePipeline.java:425)
	at org.cloudbus.cloudsim.hosts.HostSimple.getUtilizationOfCpuMips(HostSimple.java:781)
	at org.cloudbus.cloudsim.hosts.HostSimple.updateProcessing(HostSimple.java:203)
	at org.cloudbus.cloudsim.datacenters.DatacenterSimple.updateHostsProcessing(DatacenterSimple.java:583)
	at org.cloudbus.cloudsim.datacenters.DatacenterSimple.updateCloudletProcessing(DatacenterSimple.java:643)
	at org.cloudbus.cloudsim.datacenters.DatacenterSimple.processVmEvents(DatacenterSimple.java:200)
	at org.cloudbus.cloudsim.datacenters.DatacenterSimple.processEvent(DatacenterSimple.java:160)
	at org.cloudbus.cloudsim.core.CloudSimEntity.run(CloudSimEntity.java:310)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.cloudbus.cloudsim.core.CloudSim.executeRunnableEntities(CloudSim.java:448)
	at org.cloudbus.cloudsim.core.CloudSim.runClockTickAndProcessFutureEvents(CloudSim.java:381)
	at org.cloudbus.cloudsim.core.CloudSim.eventLoop(CloudSim.java:235)
	at org.cloudbus.cloudsim.core.CloudSim.start(CloudSim.java:212)
	at br.ufla.grubicom.cloud.sim.EvolvingWeightsSimulation.main(EvolvingWeightsSimulation.java:149)
```

This exception was raised when trying to assign different PlanetLab traces to different cloudlets. Below is the cloudlet creation method:

```
private static Cloudlet createCloudlet(int id) {
        
        java.io.File folder = new java.io.File("~/NetBeansProjects/cloudsim-plus/cloudsim-plus-examples/src/main/resources/workload/planetlab/20110303/");
        java.io.File[] fileList = folder.listFiles();
        
        Cloudlet cloudlet = new CloudletSimple(id, CLOUDLET_MI, CLOUDLET_PES);
        cloudlet.setUtilizationModel(new UtilizationModelPlanetLab(fileList[id].toString(), SCHEDULING_INTERVAL));

        return cloudlet;
        
    }
```
This exception is raised according to the number of cloudlets created. Following is the behavior of three tests made:

- When creating 30 cloudlets, the program works fine;
- When creating 50 cloudlets, the aforementioned exception was raised;
- When creating 100 cloudlets, the simulation time receives a NaN value, which prevents the computation of the total power consumption.

This bug appears on CloudSim Plus 3.0 that was built and executed in Apache Neatbeans 9.0.

**Comment by manoelcampos** [comment] 2018-08-17 18:25
Hello @alexandredias3d,
Try to use a `UtilizationModelFull` and check how long your Cloudlets take to finish.
What is the SCHEDULING_INTERVAL you used?
I'm supposing the Cloudlets are spending more time to finish than there is data in the planetlab files.

**Comment by alexandredias3d** [comment] 2018-08-17 20:17
Hi @manoelcampos,
You are right. By decreasing the length of the cloudlet or increasing the scheduling interval the problem disappears. I have been using the scheduling interval of 300 seconds in order to match Planet Lab utilization traces, but I guess my cloudlet's length was way too large.

I will probably change the UtilizationModelPlanetLab to get a random trace from the resources folder whenever this exception is raised.

Thank you!

**Comment by manoelcampos** [comment] 2018-08-17 21:08
I was thinking of creating a circular list. When the last line on the trace is read, then it restarts from the beginning.  This may be a more suitable approach. What do you think?

Anyway, if you can find a workaround for this issue meanwhile, I take a look to implement a solution afterward. I'm currently working on the issue #149 and it will take a couple of weeks to finish yet.

**Comment by alexandredias3d** [comment] 2018-08-20 14:00
I thought about computing indexes using the modulo of DATA_SAMPLES. However, I changed the UtilizationModelPlanetLab class but its behavior did not change at all. Am I missing something?

**Comment by manoelcampos** [comment] 2018-08-20 15:11
The module computation will do the trick for the circular list. Post the
changes you made so that I can evaluate. It would be great if you could
submit a pull request.

Keep in mind that you may struggle to update your fork with the latest
CloudSim Plus versions if you change the framework classes and keep the
changes private.

>

**Comment by manoelcampos** [comment] 2018-08-21 15:10
The warning is due to a CloudSim issue that was fixed in CloudSim Plus but the examples were not updated accordingly. In CloudSim, the RAM UtitilizationModelFull for each Cloudlet was using 100% of the VM's RAM capacity. However, if there are, for instance, 2 Clouldets running simultaneously inside the same VM, the total RAM utilization will be 200%, that is not possible without virtual memory. In CloudSim Plus, if a Cloudlet tries to use more resource than is available, that warning is issued.
To avoid the warning, instead of using a UtilizationModelFull for Cloudlets that run simultaneously inside a VM, a UtilizationModelDynamic that requires just a fraction of the RAM capacity can be used instead.

About the exception, the reason is that the computed utilization is being returned as a negative value.
I suppose the issue is in the last line of the method below:
```java
private double getUtilizationPerSec(final double time) {
  final int prevIndex = getPrevUtilizationIndex(time);
  final int nextIndex = getNextUtilizationIndex(time);

  return (utilization[nextIndex] - utilization[prevIndex]) / getSecondsInsideInterval(prevIndex, nextIndex);
}
```

It's computing the different from the nextIndex with the prevIndex, that may return a negative number when the former is lower than the latter. If we have 5 - 7 = -2, it means the utilization reduce 2 points from the next to the previous value. If it was 7 - 5 = 2, it means the utilization increased 2 points. In either case, the utilization for the period is 2 points. 
This way, we just need to change the return as 
`return Math.abs(utilization[nextIndex] - utilization[prevIndex]) / getSecondsInsideInterval(prevIndex, nextIndex);` 
However, it will be needed to include new test cases to ensure everything is OK.

**Comment by alexandredias3d** [comment] 2018-08-21 15:29
I thought this negative utilization was not wrong since the original UtilizationModelPlanetLab does return negative values. I printed out the return values for a small Cloudlet and it does return some negative values and it executes without error. Here is the sequence of utilization values returned by the function (only unique values are being presented):
`0.0, 6.666666666666666E-5, -1.333333333333333E-4, 6.666666666666667E-5, 1.6666666666666666E-4, -2.333333333333333E-4`

**Comment by manoelcampos** [comment] 2018-08-21 17:50
If you tried in CloudSim, it may return negative values for the `double getUtilization(final double time)` method, but it doesn't raise an exception because such an exception was introduced in CloudSim Plus.

The method above returns the resource utilization for a given time. It doesn't make sense a negative utilization. The minimum amount that a resource can be used is zero. The `getUtilizationPerSec(time)` may return a negative value because it represents the difference from the nextIndex to the prevIndex as I mentioned before. If it's negative, the resource usage decreased since the prevIndex.

**Comment by alexandredias3d** [comment] 2018-08-21 18:15
I am using CloudSim Plus. If I understood correctly, this exception is raised  when calling the function `protected void validateUtilizationField(final String fieldName, final double fieldValue, double minValue)`, however this function is not being called anywhere on UtilizationModelPlanetLab.

I made the changes you suggested and the VM is being destroyed while the cloudlet is still running. I am trying to run just one large cloudlet inside one VM. Since the cloudlet is never finished, the results table is empty.

**Comment by manoelcampos** [comment] 2018-08-21 18:48
The exception you showed first is happening inside the `PowerModelAbstract.getPower()` method. It's a different exception. I have to finish the issue I'm working on to check this one. It will take about one more week. Meanwhile, if you can't find the source of the issue, you can try to duplicate the content of the trace file as a workaround.

**Comment by manoelcampos** [comment] 2018-08-28 17:21
Hello @alexandredias3d 
Could you please try the version available at the [dev branch](https://github.com/manoelcampos/cloudsim-plus/tree/dev) with your simulations and give me some feedback?

If you want to, check the commit message and the new comments in the UtilizationModelPlanetLab class.

**Comment by alexandredias3d** [comment] 2018-08-28 19:12
Hi @manoelcampos, I have tested your changes but I still get the same error. I thought that it could be due to the lack of the modulo computation on `getPrevUtilizationIndex`, but even after implementing it my simulations still raise the java.lang.IllegalArgumentException.

I will rewrite my simulations from scratch to see if I haven't messed up anything else.

**Closed** 2018-08-28 23:32 UTC
Labels: bug, in-progress

**Comment by manoelcampos** [comment] 2018-08-28 23:50
Well, the ArrayIndexOutOfBoundsException related to this issue was fixed. I've just made some small changes. Check the documentation of the `getIntervalSize()` method. The changes are merged into the master branch. You can try again.

Anyway, are you getting the error 
`java.lang.IllegalArgumentException: Utilization value must be between 0 and 1. The given value was -XXXX at PowerModelAbstract.getPower(PowerModelAbstract.java:36)` using the changes I've just made?

If so, could you provide a minimalist example showing the issue?
