### ISSUE TITLE
Running CloudSim Plus Network example throws NullPointerException and Maven Failure

### ISSUE THREAD

**Issue by jlxcsy** [manoelcampos/cloudsim-plus#131] opened 2018-05-13 12:37 UTC
I am new to CloudSim Plus and  planning to implement my network protocol in the cloudsim.
After installing Java/Maven/NetBeans successfully , I tried to run NetworkExample1.java.
But it came out with NullPointerException and Maven Failure.

Q1: I guess the missing "topology.brite" results in  NullPointerException. Is that so?
Could you give us an Example of topology.brite ?

Q2: And I don't know why Maven failed with the hint "Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project cloudsim-plus-examples: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]"
How can I fix them?

1.Here is my platform info:
![1](https://user-images.githubusercontent.com/7589089/39967413-49ed4ffc-56aa-11e8-8792-5adea121e24c.jpg)

2.Here is total output after running NetworkExample1.java:

cd /home/iser/cloudsim-plus-master/cloudsim-plus-examples; JAVA_HOME=/java/jdk1.8.0_172 /home/iser/netbeans-8.2/java/maven/bin/mvn "-Dexec.args=-classpath %classpath org.cloudbus.cloudsim.examples.network.NetworkExample1" -Dexec.executable=/java/jdk1.8.0_172/bin/java -Dexec.classpathScope=runtime org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building CloudSim Plus Examples 2.3.0
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ cloudsim-plus-examples ---
Starting NetworkExample1...
Starting CloudSim Plus 2.3.0
DatacenterSimple1 is starting...
Exception in thread "main" java.lang.NullPointerException
	at org.cloudbus.cloudsim.network.topologies.BriteNetworkTopology.getDelay(BriteNetworkTopology.java:216)
	at org.cloudbus.cloudsim.core.CloudSimEntity.getNetworkDelay(CloudSimEntity.java:506)
	at org.cloudbus.cloudsim.core.CloudSimEntity.send(CloudSimEntity.java:442)
	at org.cloudbus.cloudsim.core.CloudSimEntity.sendNow(CloudSimEntity.java:478)
	at org.cloudbus.cloudsim.datacenters.DatacenterSimple.startEntity(DatacenterSimple.java:837)
	at org.cloudbus.cloudsim.core.CloudSimEntity.start(CloudSimEntity.java:97)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.cloudbus.cloudsim.core.CloudSim.startEntitiesIfNotRunning(CloudSim.java:634)
	at org.cloudbus.cloudsim.core.CloudSim.start(CloudSim.java:207)
	at org.cloudbus.cloudsim.examples.network.NetworkExample1.<init>(NetworkExample1.java:133)
	at org.cloudbus.cloudsim.examples.network.NetworkExample1.main(NetworkExample1.java:56)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 5.616s
Finished at: Sun May 13 20:17:39 CST 2018
Final Memory: 6M/59M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project cloudsim-plus-examples: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by manoelcampos** [comment] 2018-05-13 20:43
The issue is not related to the topology.brite, since the file exists
inside the resources directory.
It was because some entities such as the CloudInformationService, aren't
mapped to BRITE entities,
since it isn't a network component.

Update your fork and execute mvn clean install inside the project's root
folder.

*Manoel Campos da Silva Filho* *Software Engineer*

*Computer Science and Engineering **Ph.D.** Student at University of Beira
Interior (Portugal)*

*Professor at Federal Institute of Education, Science and Technology of
Tocantins (Brazil)*

http://manoelcampos.com


<http://about.me/manoelcampos> about.me <http://about.me/manoelcampos>

**Comment by manoelcampos** [comment] 2018-05-18 13:06
It was closed by commit b20d6f777dcfe835fd8a9ec498ceb3a31f00ce32.

**Closed by manoelcampos** 2018-05-18 13:06 UTC

**Comment by jlxcsong** [comment] 2018-06-07 08:41
I'm wondering if cloudsimplus could simulates comunications between hosts or vms in the cloud at package layer which maybe like heartbeat protocol or 3-way handshake protocol.

**Comment by jlxcsong** [comment] 2018-06-07 09:12
can we make cloudlet more specific, not just filesize or outputsize?

**Comment by manoelcampos** [comment] 2018-06-07 10:02
I've just realized you changed the text of an existing issue to ask a question.
You **MUST NOT** do that since you are destroying the project's documentation. If you'd like support, first read the instructions in the README file and subscribe to the forum. You also must read the forum instructions if you want your questions to be answered.

**Comment by manoelcampos** [comment] 2018-06-07 10:14
Sorry, I confused issues with the same title. Anyway, if you want support, subscribe to the forum. You also must read the forum instructions if you want your questions to be answered.
